Feature/config/vscode extensions
givery-bootcamp/dena-2024-team1 pull request #28
Opened 2024-05-27 17:01 UTC by ayumu-1212

## 概要

- [x] vscodeの推奨拡張機能を追加しました
- [x] linter, formatterの設定をしました
- [x] linterの設定に伴い既存のコードを修正しました 

## レビューの観点

以下の手順が再現するか

1. このブランチをlocalに持ってくる
1. vscodeの拡張機能をinstall する
  - [ ] goが推奨されることを確認
![スクリーンショット 2024-05-28 2 01 29](https://github.com/givery-bootcamp/dena-2024-team1/assets/50935536/017b1f41-678c-4031-900d-b00c579ba9f6)

## 解決するIssue

- Closes #27 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

2024-05-28 01:12 UTC, watagit requested changes

2024-05-28 01:12 UTC, watagit commented on backend/main.go
> ここまで終わったら、おそらくgoファイルを保存するたびにlintとformatter がきくはずなので、goファイルを開いて適当な空行入れて保存してみてください

1点認識合ってるか確認！
適当に空行入れて保存しても空行は残ったままなんだけど、これは期待通りという理解で大丈夫かな？

![image](https://github.com/givery-bootcamp/dena-2024-team1/assets/44804976/12e9de7a-6758-4451-9942-abb08f77a1be)

2024-05-28 01:15 UTC, ayumu-1212 commented on backend/main.go
レビューあざす！
`cmd + s`してもそうなる？

2024-05-28 08:45 UTC, kmkz01 approved these changes
動いた

2024-06-11 02:17 UTC, watagit approved these changes

2024-06-11 02:18 UTC, merged