投稿一覧画面のAPI繋ぎ込み
givery-bootcamp/dena-2024-team1 pull request #70
Opened 2024-06-17 07:59 UTC by nt240

## 概要

バックエンドから投稿一覧を取得し、投稿一覧画面で表示されるようにした

## スクリーンショット

<img width="1439" alt="スクリーンショット 2024-06-17 16 58 06" src="https://github.com/givery-bootcamp/dena-2024-team1/assets/95955238/bde31052-5b9e-446c-a2ab-36e8615380ac">

## レビューの観点

## 解決するIssue

- Closes #34

2024-06-17 08:24 UTC, watagit requested changes

2024-06-17 08:24 UTC, watagit commented on frontend/src/shared/services/API.ts
> +
todoなので消しちゃおう！
```suggestion
```

2024-06-17 08:24 UTC, watagit commented on frontend/src/shared/services/API.ts
> +  */
コメントアウト部分は使わないから消しちゃいやしょ

2024-06-17 08:24 UTC, watagit commented on frontend/src/shared/services/API.ts
> +
ここの差分もなくて良さそう

2024-06-17 08:24 UTC, watagit commented on frontend/src/shared/services/client.ts
authored by copilotだけど、↓だとany使わずに動いた
```ts
import axios, { AxiosResponse , AxiosInstance } from "axios";
import { mapKeys, camelCase, mapValues, isArray, isObject } from "lodash";

type ApiResponse<T> = {
  data: T
} & AxiosResponse

const API_ENDPOINT_PATH: string = import.meta.env.VITE_API_ENDPOINT_PATH ?? "";
export const client: AxiosInstance = axios.create({ baseURL: API_ENDPOINT_PATH });

const mapKeysDeep = <T>(data: T, callback: (value: unknown, key: string) => string): T => {
  if (isArray(data)) {
    return data.map(innerData => mapKeysDeep(innerData, callback)) as T;
  } else if (isObject(data)) {
    return mapValues(mapKeys(data, callback), val =>
      mapKeysDeep(val, callback),
    ) as T;
  } else {
    return data;
  }
};

const mapKeysCamelCase = <T>(data: T): T =>
  mapKeysDeep(data, (_: unknown, key: string) => camelCase(key));

client.interceptors.response.use(
  (response: AxiosResponse<unknown, unknown>) => {
    const { data } = response;
    const convertedData = mapKeysCamelCase(data);
    return { ...response, data: convertedData } as ApiResponse<unknown>;
  },
  (error) => {
    console.log(error);
    return Promise.reject(error);
  },
);
```

2024-06-17 08:24 UTC, watagit commented on frontend/src/features/posts/PostItem.tsx
> +}
[imo]
日付周りの処理は[dayjs](https://github.com/iamkun/dayjs/blob/dev/docs/ja/README-ja.md)とかの外部ライブラリ使った方が可読性が高いからおすすめしたいかも
外部ライブラリ使わない場合はどういうフォーマットの日付が関数から返ってくるかコメントで書いておいてもらえるとわかりやすい 🙏

2024-06-17 08:26 UTC, nt240 commented on frontend/src/shared/services/API.ts
> +
消した

2024-06-18 04:13 UTC, watagit requested changes

2024-06-18 04:13 UTC, watagit commented on frontend/src/shared/services/API.ts
ここなんだけど、openapi-generator-cliから生成されたインターフェースを使った方が便利だから置き換えちゃっていいと思う！
```ts
import { Post, PostApi } from "~/generated";

export const getPosts = createAsyncThunk<Post[]>("getPosts", async () => {
  const postApi = new PostApi();
  const response = await postApi.getAllPosts();
  return response.data;
});
```

2024-06-18 04:13 UTC, watagit commented on frontend/src/shared/services/API.ts
> +
[nits]
この空行は不要そう
```suggestion
```

2024-06-18 05:04 UTC, watagit approved these changes
LGTM!

2024-06-18 05:04 UTC, merged